version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"    
    network_mode: "host"
    depends_on:
      - redis  
  redis:
    image: "redis"
    ports:
      - "6379:6379"